# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=20, verbose_name='\u4e3b\u673a\u540d')),
                ('os', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu_model', models.CharField(max_length=50, verbose_name='CPU\u578b\u53f7')),
                ('cpu', models.CharField(max_length=50, verbose_name='CPU')),
                ('mem', models.CharField(max_length=50, verbose_name='\u5185\u5b58')),
                ('disk', models.CharField(max_length=50, verbose_name='\u786c\u76d8')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['ip'],
                'verbose_name': '\u8d44\u4ea7\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u8d44\u4ea7\u4fe1\u606f\u8868',
            },
        ),
    ]
