# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=20, verbose_name='\u4e3b\u673a\u540d')),
                ('cpu', models.PositiveIntegerField(verbose_name='CPU')),
                ('mem', models.PositiveIntegerField(verbose_name='\u5185\u5b58')),
                ('dick', models.PositiveIntegerField(verbose_name='\u786c\u76d8')),
            ],
        ),
    ]
