# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-12 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.CharField(max_length=50, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='IP\u5730\u5740'),
        ),
    ]
