# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-06 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['ip_pub'], 'verbose_name': '\u4e3b\u673a\u4fe1\u606f\u8868', 'verbose_name_plural': '\u4e3b\u673a\u4fe1\u606f\u8868'},
        ),
        migrations.RemoveField(
            model_name='host',
            name='ip',
        ),
        migrations.AddField(
            model_name='host',
            name='ip_prv',
            field=models.GenericIPAddressField(default='1.1.1.1', verbose_name='\u5185\u7f51IP\u5730\u5740'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='ip_pub',
            field=models.GenericIPAddressField(default='1.1.1.1', verbose_name='\u5916\u7f51IP\u5730\u5740'),
            preserve_default=False,
        ),
    ]
