# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-12 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170812_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='dick',
        ),
        migrations.AddField(
            model_name='host',
            name='disk',
            field=models.CharField(default=2, max_length=50, verbose_name='\u786c\u76d8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='mem',
            field=models.CharField(max_length=50, verbose_name='\u5185\u5b58'),
        ),
    ]
