# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-12 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170812_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpu_model',
            field=models.CharField(default=1, max_length=50, verbose_name='CPU\u578b\u53f7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.CharField(default=1, max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
            preserve_default=False,
        ),
    ]
