# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_host_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='pwd',
        ),
        migrations.AddField(
            model_name='host',
            name='pwd_root',
            field=models.CharField(default=1, max_length=50, verbose_name='root\u767b\u5f55\u5bc6\u7801'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='pwd_user',
            field=models.CharField(default=1, max_length=50, verbose_name='\u666e\u901a\u7528\u6237\u767b\u5f55\u5bc6\u7801'),
            preserve_default=False,
        ),
    ]
