# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-31 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20180129_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d'),
        ),
    ]
